Repository icl-utk-edu/papi, pull requests merged in 2025-01, with the labels that each got.

#273 Workflow Updates for PAPI GitHub CI
  .github/workflows/README.md
  .github/workflows/appio_component_workflow.yml
  .github/workflows/cat_workflow.yml
  .github/workflows/ci.sh
  .github/workflows/ci_cat.sh
  .github/workflows/ci_default_components.sh
  .github/workflows/ci_individual_component.sh
  .github/workflows/ci_papi_framework.sh
  .github/workflows/coretemp_component_workflow.yml
  .github/workflows/cuda_component_workflow.yml
  .github/workflows/default_components_workflow.yml
  .github/workflows/example_component_workflow.yml
  .github/workflows/intel_gpu_component_workflow.yml
  .github/workflows/io_component_workflow.yml
  .github/workflows/lmsensors_component_workflow.yml
  .github/workflows/main.yml
  .github/workflows/net_component_workflow.yml
  .github/workflows/nvml_component_workflow.yml
  .github/workflows/papi_framework_workflow.yml
  .github/workflows/powercap_component_workflow.yml
  .github/workflows/rocm_component_workflow.yml
  .github/workflows/rocm_smi_component_workflow.yml
  .github/workflows/sde_component_workflow.yml
  .github/workflows/stealtime_component_workflow.yml
  src/run_tests.sh
  src/run_tests_shlib.sh
Labels: status-ready-to-merge, update-ci, priority-normal

#301 Fix for Bug in Counter Analysis Toolkit Workflow for PAPI CI
  .github/workflows/cat_workflow.yml
Labels: type-bug, priority-high, update-ci

#281 2024.11.12 cat bug
  src/counter_analysis_toolkit/eventstock.c
  src/counter_analysis_toolkit/main.c
Labels: type-bug, counter-analysis-toolkit

#257 perf_event: Eliminate paranoia error for check_exclude_guest()
  src/components/perf_event/perf_event.c
Labels: component-perf_event, status-ready-for-review

#305 Update run_tests.sh to remove bash specific syntax
  src/run_tests.sh
Labels: type-bug, status-ready-for-review

#295 Update libpfm4 to commit 69550d
  src/libpfm4/include/perfmon/perf_event.h
  src/libpfm4/lib/events/arm_neoverse_n1_events.h
  src/libpfm4/lib/events/arm_neoverse_n2_events.h
  src/libpfm4/lib/events/arm_neoverse_v1_events.h
  src/libpfm4/lib/events/arm_neoverse_v2_events.h
Labels: status-ready-for-review, update-libpfm4, priority-normal

#296 Updating papi_events.csv to support addition of L1I_CACHE in libpfm4
  src/papi_events.csv
Labels: status-ready-for-review, update-presets, priority-normal

#310 Replace actions/upload-artifact@v3 with actions/upload-artifact@v4
  .github/workflows/papi_framework_workflow.yml
Labels: status-ready-for-review, update-ci
